### ISSUE TITLE
[Backend] init.sh의 virtualenv 가 제대로 activate되지 못하는 문제

### ISSUE THREAD

**Issue by DHdroid** [swsnu/swpp2019-team21#52]
./init.sh 로 스크립트를 실행해도 스크립트의 명령어가 venv가 activate 되지 않은 채로 진행됩니다.

**Comment by csh3695** [comment]
https://github.com/swsnu/swpp2019-team21/commit/d7748acde5f3abf5d0d79eccb0ade04b929d3b4e

해결됐나요?

**Comment by DHdroid** [comment]
> [d7748ac](https://github.com/swsnu/swpp2019-team21/commit/d7748acde5f3abf5d0d79eccb0ade04b929d3b4e)
> 
> 해결됐나요?

이런 에러 메시지가 나옵니다. 
django.core.exceptions.ImproperlyConfigured: mysqlclient 1.3.13 or newer is required; you have 0.9.3.
아마 pymysql의 내부 문제로 추정되며, 이를 base.py의 설정을 강제로 바꾸는 방식으로 해결해도

No module named 'numpy.random._pickle' 와 같은 에러 메시지가 나옵니다.

**Comment by DHdroid** [comment]
> 아마 pymysql의 내부 문제로 추정되며, 이를 base.py의 설정을 강제로 바꾸는 방식으로 해결해도

확인 해보니 여전히 venv가 실행되지 않습니다.

**Comment by csh3695** [comment]
https://github.com/swsnu/swpp2019-team21/commit/f97704f0e0e2463e6bca328877e9cee3e33a2396
이건?

**Comment by DHdroid** [comment]
> [f97704f](https://github.com/swsnu/swpp2019-team21/commit/f97704f0e0e2463e6bca328877e9cee3e33a2396)
> 이건?

django is not working now

**Comment by DHdroid** [comment]
> [f97704f](https://github.com/swsnu/swpp2019-team21/commit/f97704f0e0e2463e6bca328877e9cee3e33a2396)
> 이건?

pip install 이 제대로 작동하지 않는 것 같습니다. pip3로도 테스트 했으나 동일

**Comment by csh3695** [comment]
https://github.com/swsnu/swpp2019-team21/commit/92d81a5bce5bf81662f29767e74ef5a9a0f6a6e6 resolved. Thanks.
