### ISSUE TITLE
[UI] UI to be fixed

### ISSUE THREAD

**Issue by csh3695** [swsnu/swpp2019-team21#72]
- AOS on main page and search page differ
- Post Content no break at new line
- Article Edit/link copy button color differ
- SNS onhover and onclick no reaction(shadow change /click modal...)
- Article Detail : 번 포인트 -> 얻은 포인트
- Preview UI change
- UserDetail UI change

**Comment by sanggggg** [comment]
* [ ] AOS on main page and search page differ 
* [ ] Post Content no break at new line
* [ ] Article Edit/link copy button color differ
* [ ] SNS onhover and onclick no reaction(shadow change /click modal...)
* [ ] Preview UI change
* [ ] UserDetail UI change

**Comment by csh3695** [comment]
Thanks. Done.
