### ISSUE TITLE
[Alpha Testing] Clicking profile

### ISSUE THREAD

**Issue by desiderare** [swsnu/swpp2019-team21#77]
매우매우 사소한 것이지만 로그아웃이나 제 정보를 보기 위해 우측 상단의 어카운트 이미지를 클릭하면 나오는 My page를 클릭하면 그 해당 창이 자동으로 꺼지는 것이 더 자연스러울 것 같습니다. 현재는 My page에 들어가도 여전히 그 창이 켜져 있어서 수동으로 꺼주어야 합니다.

**Comment by sanggggg** [comment]
오! 감사합니다... 좋은 의견이군요 수정하겠습니다
