### ISSUE TITLE
[alpha testing] search keyword issue

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team21#78]
<img width="1440" alt="스크린샷 2019-12-05 오후 7 41 29" src="https://user-images.githubusercontent.com/17784659/70228231-57dfb280-1797-11ea-9d05-00a0ed177b89.png">

키워드를 설정한 후 다른 곳을 클릭한 다음 다시 검색창을 클릭하면 검색 키워드 수정이 불가능합니다.

**Comment by sanggggg** [comment]
텍스트가 남아있지만 키보드로 입력시 수정이 되긴합니다, UI의 문제이므로 빠르게 수정하겠습니다
