### ISSUE TITLE
[alpha testing] mypage when not logged in

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team21#81]
<img width="1440" alt="스크린샷 2019-12-05 오후 7 46 33" src="https://user-images.githubusercontent.com/17784659/70228642-0552c600-1798-11ea-88a0-260803fa6e2c.png">

로그인하지 않은 상태에서 `https://www.adit.shop/mypage` 가 접속가능합니다.

**Comment by sanggggg** [comment]
감사합니다!

**Comment by digdhg** [comment]
수정하도록 하겠습니다. 감사합니다!

**Comment by digdhg** [comment]
Done
