### ISSUE TITLE
[Alpha Testing] Does not sanitize file upload

### ISSUE THREAD

**Issue by taehioum** [swsnu/swpp2019-team21#82]
We can upload arbitrary files to image file. I think this can be a security hole.

**Comment by digdhg** [comment]
We check that when you submit. you can only submit jpeg, jpg, png file. Than you :)

**Comment by taehioum** [comment]
I uploaded a .bat file and didn't get any warnings.

**Comment by csh3695** [comment]
Resolved. Thanks.
